### ISSUE TITLE
Replication of '$:/status/UserName'

### ISSUE THREAD

**Issue by elliott5** [danielo515/tiddlypouch#91]
Hi Daniel, this is not an immediate issue for me, but I thought I should report it.

I noticed that '$:/status/UserName' is currently being synced to the remote database. In a multi-user setting, this tiddler should surely not be synced.

So I'd propose the return statement in `startup/startup-syncer.js` : `buildFilterView()` be changed to:
```
return (doc.hasOwnProperty('fields') && doc.fields.title !== '$:/StoryList' && doc.fields.title !== '$:/status/UserName');
```
But I then noticed, than on my database (which was created a year ago) '$:/StoryList' was also being replicated (which the existing code should not permit). 
This replication occurred because the `_design/filtered_replication` record(s) are not being updated in either database because of an update conflict.
So in order for existing projects to get revised `_design/filtered_replication` records, and therefore operate correctly, `buildFilterView()` needs to be altered to do an update (rather than the current failing insert).
To do an update it needs to set the current `rev` number in the record that is passed to `db.put(...)`.
My suggestion would be to pass the database object `buildFilterView(db)` so that a `db.get(...)` can be done to find the `rev` to include in the record to return from the function.

Hope that helps.

**Comment by danielo515** [comment]
Hello @elliott5 ,

Thank you very much for your detailed report. Sadly I don't have much time these days.
I have to admit that never thought about multi user scenarios when I added the functionality to save `status/UserName`. I just wanted to provide the ability to persist your user name.
The upgrade process is something that should be improved, I agree.

If you feel that you can don't hesitate on opening a pull request.

Regards

**Comment by danielo515** [comment]
This will be included in the next NoteSelf release
